theme: jekyll-theme-cayman
title: MIC-PHY <br/> 15th-17th February 2021
description: The virtual MIC-Phy will be happening here!
navbar-links:
  About Me: "aboutme"
  Author's home: "https://deanattali.com"
