theme: jekyll-theme-cayman
title: MIC-PHY <br/> 15th-17th February 2021
description: The virtual MIC-Phy will be happening here!
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
