theme: jekyll-theme-minimal
title: MIC-PHY <br/> 15th-17th February 2021
description: The virtual MIC-Phy will be happening here!
navigation:
  - title: Home
    url: /
  - title: Setup
    url: LICENCE


