plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
theme: jekyll-theme-minimal
title: GitHub pages template
description: A simple template based on minimal jekyll theme
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
